### ISSUE TITLE
FIX: [CLIMATE WALLET] Retirement shows as an increment in txn history

### ISSUE THREAD

**Issue by ccornick** [Chia-Network/Climate-Wallet#118]
This should be shown as a decrement in the txn history.

**Comment by fizpawiz** [comment]
Actually, maybe that's the way to detect a retirement.  If the type is Send and the amount is positive, then it is a retirement, and change the type to Retire and the amount to be negative.  Maybe worth a try?  Bit of a hack, but I doubt we get much useful info out of the Chia Wallet for retirement spends.
